import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body className={inter.className}>
    
          <nav>
            
            <p><Link href="/produtos/bone">BONÉ</Link></p>
            <p><Link href="/produtos/calca">CALÇA</Link></p>
            <p><Link href="/produtos/camisa">CAMISA</Link></p>
            <p><Link href="/produtos/oculos">ÓCULOS</Link></p>
            <p><Link href="/produtos/sapato">SAPATO</Link></p>

          </nav>
       
        {children}
        
      </body>
    </html>
  )
}
