import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body className={inter.className}>
    
          <nav>
            
            

          </nav>
      
        {children}
        <h2>LISTA DE PRODUTOS</h2>
        
        <Image src="/img/calca.jpg" alt='calca' width={50} height={50}/>
          <Link href="/produtos/calca"></Link>

          <Image src="/img/bone.png" alt='bone' width={50} height={50}/>
          <Link href="/produtos/bone"></Link>

          <Image src="/img/camisa.png" alt='camisa' width={50} height={50}/>
          <Link href="/produtos/camisa"></Link>

          <Image src="/img/oculos.jpg" alt='oculos' width={50} height={50}/>
          <Link href="/produtos/oculos"></Link>

          <Image src="/img/sapato.jpg" alt='sapato' width={50} height={50}/>
          <Link href="/produtos/sapato"></Link>
        
            
           
      </body>
    </html>
  )
}
